/**
 * Every piece of text the panel shows, in English. Elements and helpers import from here;
 * nothing else writes user-facing text. Strings with a value are functions.
 */

const size = (width: number, height: number): string => `${width} × ${height}`;

export const strings = {
  common: {
    increase: "Increase",
    decrease: "Decrease",
    cancel: "Cancel",
    close: "Close",
    size,
    sizeInPixels: (width: number, height: number): string =>
      `${size(width, height)} px`,
    milliseconds: (value: number): string => `${value.toFixed(1)} ms`,
  },

  commands: {
    undo: "Undo",
    redo: "Redo",
    delete: "Delete",
    hide: "Hide",
    show: "Show",
    lock: "Lock",
    unlock: "Unlock",
    group: "Make group",
    ungroup: "Ungroup",
    enterGroup: "Enter group",
    exitGroup: "Exit group",
    deselect: "Deselect",
    copy: "Copy",
    cut: "Cut",
    paste: "Paste",
    pasteHere: "Paste here",
    duplicate: "Duplicate",
    rename: "Rename",
    bringToFront: "Bring to front",
    sendToBack: "Send to back",
    moveUp: "Move up",
    moveDown: "Move down",
    save: "Save dashboard",
    toggleCode: "Switch between design and code",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    zoomReset: "Reset zoom",
    showShortcuts: "Keyboard shortcuts",
    nudge: {
      left: "Nudge left",
      right: "Nudge right",
      up: "Nudge up",
      down: "Nudge down",
    },
  },

  app: {
    loading: "Loading OpenDisplay Studio…",
    loadFailed: "Could not load OpenDisplay Studio",
    createFailed: "Could not create the dashboard",
    sentToDevice: "Sent to the device",
    sendFailed: "Could not send the dashboard to the device",
    saveFailed: "Could not save the dashboard",
    deleteFailed: "Could not delete the dashboard",
    renameFailed: "Could not rename the dashboard",
    duplicateFailed: "Could not duplicate the dashboard",
    settingsFailed: "Could not update dashboard settings",
    previewFailed: "Could not render the preview",
    renameEmpty: "Dashboard name cannot be empty",
    discardChanges: "Discard unsaved dashboard changes?",
    unsupportedPrimitive: (type: string): string =>
      `Unsupported primitive type: ${type || "(empty)"}`,
    confirmRemoval: "Confirm removal",
    deleteElementTitle: (name: string): string => `Delete ${name}?`,
    deleteElementsTitle: (count: number): string => `Delete ${count} elements?`,
    deleteContainerBody:
      "This removes the container and everything in it. You can restore it with Undo.",
    deleteElementBody:
      "This removes the element from the dashboard. You can restore it with Undo.",
    deleteElement: "Delete element",
  },

  gallery: {
    title: "Dashboards",
    count: (count: number): string =>
      `${count} ${count === 1 ? "dashboard" : "dashboards"}`,
    newDashboard: "New dashboard",
    addDashboard: "Add dashboard",
    filters: "Dashboard filters",
    search: "Search dashboards",
    searchPlaceholder: "Search dashboards…",
    sort: "Sort",
    sortDashboards: "Sort dashboards",
    sortUpdated: "Last updated",
    sortName: "Name A–Z",
    savedDashboards: "Saved dashboards",
    noResults: "No dashboards found",
    noResultsHint: "Try a different search.",
    updated: (date: string): string => `Updated ${date}`,
    open: (name: string): string => `Open dashboard ${name}`,
    actionsFor: (name: string): string => `Dashboard actions for ${name}`,
    menuFor: (name: string): string => `Actions for ${name}`,
    renameField: (name: string): string => `Rename dashboard ${name}`,
    menu: {
      rename: "Rename",
      duplicate: "Duplicate",
      settings: "Display Settings",
      delete: "Delete",
    },
    deleteTitle: "Delete dashboard?",
    deleteBody: "and all of its elements will be permanently removed.",
    deleteWarning: "This action cannot be undone.",
    deleteAction: "Delete dashboard",
    deleting: "Deleting…",
    settingsTitle: "Display settings",
    settingsSave: "Save changes",
    saving: "Saving…",
  },

  newDashboard: {
    title: "New dashboard",
    subtitle: "Create a custom OpenDisplay canvas",
    startFrom: "Start from",
    sources: "Dashboard source",
    fromDevice: "From device",
    fromDeviceHint: "Size and colors",
    preset: "Predefined display",
    presetHint: "Pick a known display",
    customSize: "Custom size",
    customSizeHint: "Set size and colors",
    device: "Device",
    display: "Display",
    loadingDevices: "Looking for OpenDisplay devices…",
    noDevices:
      "No OpenDisplay devices found. Set up the OpenDisplay integration, or start from a predefined display.",
    deviceDetails: "Dashboard size and colors",
    colors: "Colors",
    create: "Create dashboard",
    creating: "Creating…",
  },

  header: {
    studio: "OpenDisplay Studio",
    dashboards: "Dashboards",
    name: "Dashboard name",
    view: "Dashboard view",
    design: "Design",
    code: "Code",
    setDraft: "Set Draft",
    setReady: "Set Ready",
    sendToDevice: "Send to device",
    sendingToDevice: "Sending…",
    save: "Save",
    saving: "Saving…",
    help: "Keyboard shortcuts",
  },

  library: {
    title: "Library",
    heading: "Elements",
    expand: "Expand element catalog",
    collapse: "Collapse element catalog",
    search: "Search widgets and primitives",
    searchPlaceholder: "Search elements…",
    widgets: "Widgets",
    primitives: "Primitives",
    containers: "Containers",
    container: "Container",
    containerHint: "Holds other elements and moves them together.",
    noContainers: "No matching containers",
    noWidgets: "No matching widgets",
    reloadWidgets: "Reload widgets",
    userWidget: "user",
    widgetErrors: (count: number): string =>
      `${count} widget ${count === 1 ? "package" : "packages"} could not be loaded`,
    widgetsReloaded: (loaded: number, failed: number): string =>
      failed === 0
        ? `Widgets reloaded — ${loaded} loaded`
        : `Widgets reloaded — ${loaded} loaded, ${failed} failed`,
    reloadFailed: "Could not reload the widgets",
    noPrimitives: "No matching primitives",
    entryHint: (description: string): string =>
      `${description} Click or drag to add.`,
  },

  shortcuts: {
    eyebrow: "Help",
    title: "Keyboard shortcuts",
    open: "Keyboard shortcuts",
    groups: {
      edit: "Edit",
      arrange: "Arrange",
      group: "Groups",
      view: "View",
      history: "History",
    },
  },

  structure: {
    title: "Structure",
    heading: "Elements",
    collapse: "Collapse inspector",
    empty: "Drag widgets or primitives onto the canvas.",
    widget: "Widget",
    reorderTitle: "Reorder layer",
    reorder: (name: string): string => `Reorder ${name}`,
    root: (count: number): string =>
      `Root (${count} ${count === 1 ? "widget" : "widgets"})`,
    rootName: "Root",
    breadcrumb: "Group being edited",
    exit: "Exit",
    container: "Container",
    group: "Group",
    groupBadge: "Group",
    search: "Search layers",
    searchPlaceholder: "Search layers…",
    rename: "Element name",
    collapseRow: (name: string): string => `Collapse ${name}`,
    expandRow: (name: string): string => `Expand ${name}`,
  },

  inspector: {
    alignInParent: "Align in Parent",
    expand: "Expand inspector",
    rail: "Layers",
    resize: "Resize inspector",
    dashboard: "Dashboard",
    dashboardHint: "Working area settings",
    workingArea: "Working area",
    workingAreaHelp:
      "Padding defines the editable safe area. Snap aligns movement and resizing to pixel increments.",
    layout: "Layout",
    widgetSettings: "Widget settings",
    background: "Background",
    backgroundEnabled: "Background",
    backgroundFill: "Fill",
    backgroundOutline: "Outline",
    backgroundWidth: "Outline width",
    backgroundRadius: "Corner radius",
    kindContainer: "Container",
    kindGroup: "Group",
    groupedChip: "Grouped",
    selectedElements: (count: number): string => `${count} elements`,
    selectionHint:
      "Move, hide, lock or delete them together. Group them to keep them as one.",
    boundingBox: "Bounding box",
    removeElements: "Remove elements",
    dataSources: "Data sources",
    widgetMissing: (type: string): string =>
      `The widget ${type} is not installed. ` +
      "It keeps its settings and draws again once the package returns.",
    appearance: "Appearance",
    diagnostics: "Render diagnostics",
    removeElement: "Remove element",
    locked: "Position is locked",
    unlock: "Unlock",
    unlockElement: "Unlock element position",
    kindWidget: "Widget",
    kindPrimitive: "ODL primitive",
    subtitle: (kind: string, locked: boolean): string =>
      `${kind} · ${locked ? "position locked" : "editable"}`,
    metrics: {
      queue: "Queue",
      data: "Data",
      compile: "Compile",
      render: "Render",
      encode: "Encode",
      total: "Total",
    },
  },

  expression: {
    toggleLabel: (field: string): string => `Expression for ${field}`,
    toggleTooltip: "Expression (or type {)",
    placeholder: "{{ states('sensor.example') }}",
    visibleLabel: "Visible",
    alwaysVisible: "Always shown",
    positionLocked: (fields: string): string =>
      `Position is driven by an expression (${fields})`,
    scalingLocked: (names: string): string =>
      `The group cannot be resized: ${names} has a position or size driven by an expression`,
    cornerFields: "Edit corners",
    derivedFields: "Edit position and size",
  },

  canvas: {
    rendering: "Rendering…",
    menuLabel: "Canvas actions",
    enterGroupHint: "Enter / double-click to edit",
    previewAlt: "Authoritative rendered display preview",
    hidden: "Hidden",
    layers: (count: number): string => `${count} layers`,
    padding: (pixels: number): string => `Padding ${pixels}px`,
    snap: (pixels: number): string => `Snap ${pixels}px`,
    resizeHandle: (name: string, side: string): string =>
      `Resize ${name} from ${side}`,
    sides: {
      nw: "north west",
      n: "north",
      ne: "north east",
      e: "east",
      se: "south east",
      s: "south",
      sw: "south west",
      w: "west",
    },
  },

  zoom: {
    out: "Zoom out",
    in: "Zoom in",
    reset: "Reset",
    fit: "Fit",
    preset: (value: number): string => `${value}×`,
  },

  code: {
    eyebrow: "Generated output",
    title: "Generated ODL YAML",
    description: "Read-only output generated from the current dashboard.",
    copyLabel: "Copy generated ODL YAML",
    yaml: "Generated ODL YAML",
    copy: { idle: "Copy YAML", copied: "Copied", failed: "Copy failed" },
    status: {
      idle: "",
      copied: "YAML copied to clipboard",
      failed: "Clipboard access failed",
    },
  },

  /**
   * Labels of form and inspector fields. One entry per concept, shared by
   * every place that shows it.
   */
  fields: {
    anchor: "Anchor",
    name: "Dashboard name",
    rotation: "Rotation",
    resolution: "Resolution",
    width: "Width",
    height: "Height",
    palette: "Palette",
    background: "Background",
    advanced: "Advanced display options",
    padding: "Outer padding",
    snapSize: "Snap size",
    x: "X",
    y: "Y",
    innerPadding: "Inner padding",
  },

  /** The generic display offered when none of the catalogued panels fits. */
  customDisplay: { manufacturer: "Custom", name: "Custom display" },

  rotations: { 0: "0°", 90: "90°", 180: "180°", 270: "270°" },

  anchors: {
    lt: "Top left",
    mt: "Top center",
    rt: "Top right",
    lm: "Middle left",
    mm: "Center",
    rm: "Middle right",
    lb: "Bottom left",
    mb: "Bottom center",
    rb: "Bottom right",
  },

  colors: {
    clear: "Clear color",
    none: "None",
    accent: "Accent",
    gray: (level: number): string => `Gray ${level}`,
    names: {
      black: "Black",
      white: "White",
      red: "Red",
      yellow: "Yellow",
      blue: "Blue",
      green: "Green",
      orange: "Orange",
    },
  },

  palettes: {
    bw: "Black / white",
    bwr: "Black / white / red",
    bwy: "Black / white / yellow",
    bwry: "Black / white / red / yellow",
    spectra6: "Spectra 6 · black / white / red / yellow / blue / green",
    seven_color: "Seven colors · Spectra 6 and orange",
    grayscale4: "Grayscale · 4 levels",
    grayscale8: "Grayscale · 8 levels",
    grayscale16: "Grayscale · 16 levels",
  },
} as const;
