"""
Write `docs/widgets/README.md` and its pictures from the widgets themselves.

Everything the page says comes from `widget.yml`, its translations and the `docs`
list of `preview.yml`, so the page cannot disagree with the widgets. Run

    python -m scripts.widget_docs

after changing a widget; a test fails while the committed page is out of date.
"""

from __future__ import annotations

import asyncio
from pathlib import Path
from typing import Any

from custom_components.opendisplay_studio.widgets import (
    BUILTIN_WIDGET_DIRECTORY,
    WidgetRegistry,
)
from scripts.widget_devkit.scenario import (
    context_for,
    draw,
    load_preview,
    load_registry,
    load_states,
    png_bytes,
    with_options,
)

DOCS = Path("docs/widgets")
IMAGES = DOCS / "images"
README = DOCS / "README.md"
INTRO = """\
# Widgets

A widget shows live Home Assistant data inside a dashboard. You pick *what* to show
(its **sources**), set *how* it looks (its **options**) and resize its frame; the
widget lays itself out to fit. Every widget has the same **Appearance** options:

* **Show frame** — draw the frame and white background (on by default). Turn it off to
  place the content straight onto the dashboard.
* **Corner radius** — how round the corners of the frame are.
* **Color** and **Background** — the color of everything drawn (text, icons,
  lines, the frame) and of what is filled behind it. They are picked from the
  colors of the display, so white on black is just two colors; on a display
  with red and yellow you can have yellow on red.

This page is generated by `python -m scripts.widget_docs`. To write your own widget see
[the widget SDK](../widget-sdk.md).
"""


def _type_of(selector: dict[str, Any]) -> str:
    kind, config = next(iter(selector.items()))
    if kind == "boolean":
        return "on / off"
    if kind == "number":
        return f"number {config['min']} to {config['max']}"
    if kind == "select":
        choices = ", ".join(f"`{option['value']}`" for option in config["options"])
        return f"one of {choices}"
    if kind == "opendisplay_color":
        return "color"
    return kind


def _default_of(value: Any) -> str:
    if isinstance(value, bool):
        return "on" if value else "off"
    if value == "":
        return "empty"
    return f"`{value}`"


def _source_type(selector: dict[str, Any]) -> str:
    kind, config = next(iter(selector.items()))
    domain = config.get("filter", {}).get("domain", "")
    count = "one or more" if config.get("multiple") else "one"
    return " ".join(part for part in (count, domain, kind) if part)


def _sources_table(definition: dict[str, Any]) -> list[str]:
    lines = ["| Source | What to pick | Per pick |", "|---|---|---|"]
    for source in definition["sources"]:
        extras = ", ".join(extra["label"] for extra in source["perSource"]) or "—"
        needed = "" if source["required"] else " (optional)"
        lines.append(
            f"| {source['label']}{needed} | {_source_type(source['selector'])}"
            f" | {extras} |"
        )
    return lines


def _options_tables(definition: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    for section in definition["options"]:
        lines += ["", f"**{section['section']}**", ""]
        lines += ["| Option | Key | Values | Default |", "|---|---|---|---|"]
        for option in section["fields"]:
            lines.append(
                f"| {option['label']} | `{option['key']}` "
                f"| {_type_of(option['selector'])} | {_default_of(option['default'])} |"
            )
    return lines


def _gallery(widget_id: str, titles: list[str]) -> list[str]:
    lines: list[str] = []
    for number, title in enumerate(titles, start=1):
        lines += ["", f"![{title}](images/{widget_id}-{number}.png)", f"*{title}*"]
    return lines


def _folder(root: Path, widget_id: str) -> Path:
    return root / widget_id.replace("-", "_")


def _widget_section(registry: WidgetRegistry, widget_id: str, root: Path) -> str:
    definition = next(
        item for item in registry.definitions() if item["id"] == widget_id
    )
    size = definition["layout"]["defaultSize"]
    minimum = definition["layout"]["minSize"]
    showcases = load_preview(_folder(root, widget_id)).showcases
    lines = [
        f"## {definition['name']}",
        "",
        definition["description"],
        "",
        (
            f"Default size {size['width']} x {size['height']} px, "
            f"smallest {minimum['width']} x {minimum['height']} px. "
            f"Id: `{widget_id}`."
        ),
        "",
        "### Sources",
        "",
        *_sources_table(definition),
        "",
        "### Options",
        *_options_tables(definition),
        "",
        "### Examples",
        *_gallery(widget_id, [showcase.title for showcase in showcases]),
    ]
    return "\n".join(lines)


def build_markdown(root: Path = BUILTIN_WIDGET_DIRECTORY) -> str:
    """Return the whole page for the widgets under `root`."""
    registry = load_registry(root)
    sections = [
        _widget_section(registry, widget_id, root)
        for widget_id in sorted(registry.widget_types)
    ]
    return INTRO + "\n" + "\n\n".join(sections) + "\n"


async def write_images(root: Path = BUILTIN_WIDGET_DIRECTORY) -> int:
    """Draw every showcase of every widget into `docs/widgets/images`."""
    registry = load_registry(root)
    IMAGES.mkdir(parents=True, exist_ok=True)
    written = 0
    for widget_id in sorted(registry.widget_types):
        folder = _folder(root, widget_id)
        preview = load_preview(folder)
        states = load_states(folder)
        sizes = {size.name: size for size in preview.sizes}
        for number, showcase in enumerate(preview.showcases, start=1):
            size = sizes[showcase.size]
            state = with_options(states[showcase.state], showcase.options)
            palette = showcase.palette or preview.palette
            context = context_for(
                registry, widget_id, state, (size.width, size.height), palette
            )
            image, _ = await draw(context, registry.renderer(widget_id))
            (IMAGES / f"{widget_id}-{number}.png").write_bytes(png_bytes(image))
            written += 1
    return written


def main() -> None:
    """Write the page and its pictures."""
    count = asyncio.run(write_images())
    README.write_text(build_markdown(), encoding="utf-8", newline="\n")
    print(f"Wrote {README} and {count} pictures")  # noqa: T201 - a command line tool


if __name__ == "__main__":
    main()
